# Configuração para Railway
[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "python main.py"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Em vez de usar proxy, implante na região de Singapura
# Use o comando: railway variables set RAILWAY_REGION=asia-southeast1-eqsg3a
[variables]
# Configure as variáveis de ambiente do bot via dashboard do Railway
