"""add_market_analysis_table

Revision ID: 498404b020d7
Revises: 8dad94ec6868
Create Date: 2025-07-08 00:35:02.435191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '498404b020d7'
down_revision = '8dad94ec6868'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
