"""add_remaining_missing_tables

Revision ID: 5dd05cdf0956
Revises: 498404b020d7
Create Date: 2025-07-08 00:40:20.558722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dd05cdf0956'
down_revision = '498404b020d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
